// @ts-nocheck -- skip type checking
import * as docs_9 from "../content/docs/databases/drizzle-orm/setup-drizzle-orm-sqlite.mdx?collection=docs&hash=1744415937639"
import * as docs_8 from "../content/docs/databases/drizzle-orm/modular-scalable-schema-design.mdx?collection=docs&hash=1744415937639"
import * as docs_7 from "../content/docs/internal/docs-knowledge.mdx?collection=docs&hash=1744415937639"
import * as docs_6 from "../content/docs/git/set-upstream.mdx?collection=docs&hash=1744415937639"
import * as docs_5 from "../content/docs/git/branch-diverged.mdx?collection=docs&hash=1744415937639"
import * as docs_4 from "../content/docs/features/webcam-tester.mdx?collection=docs&hash=1744415937639"
import * as docs_3 from "../content/docs/features/mic-tester.mdx?collection=docs&hash=1744415937639"
import * as docs_2 from "../content/docs/features/keyboard-tester.mdx?collection=docs&hash=1744415937639"
import * as docs_1 from "../content/docs/databases/validate-env-variables.mdx?collection=docs&hash=1744415937639"
import * as docs_0 from "../content/docs/attempt-to-make-OSX-decent/sudo-auto-pasword.mdx?collection=docs&hash=1744415937639"
import { _runtime } from "fumadocs-mdx"
import * as _source from "../source.config"
export const docs = _runtime.docs<typeof _source.docs>([{ info: {"path":"attempt-to-make-OSX-decent/sudo-auto-pasword.mdx","absolutePath":"/Users/remcostoeten/code/v2.snippets/content/docs/attempt-to-make-OSX-decent/sudo-auto-pasword.mdx"}, data: docs_0 }, { info: {"path":"databases/validate-env-variables.mdx","absolutePath":"/Users/remcostoeten/code/v2.snippets/content/docs/databases/validate-env-variables.mdx"}, data: docs_1 }, { info: {"path":"features/keyboard-tester.mdx","absolutePath":"/Users/remcostoeten/code/v2.snippets/content/docs/features/keyboard-tester.mdx"}, data: docs_2 }, { info: {"path":"features/mic-tester.mdx","absolutePath":"/Users/remcostoeten/code/v2.snippets/content/docs/features/mic-tester.mdx"}, data: docs_3 }, { info: {"path":"features/webcam-tester.mdx","absolutePath":"/Users/remcostoeten/code/v2.snippets/content/docs/features/webcam-tester.mdx"}, data: docs_4 }, { info: {"path":"git/branch-diverged.mdx","absolutePath":"/Users/remcostoeten/code/v2.snippets/content/docs/git/branch-diverged.mdx"}, data: docs_5 }, { info: {"path":"git/set-upstream.mdx","absolutePath":"/Users/remcostoeten/code/v2.snippets/content/docs/git/set-upstream.mdx"}, data: docs_6 }, { info: {"path":"internal/docs-knowledge.mdx","absolutePath":"/Users/remcostoeten/code/v2.snippets/content/docs/internal/docs-knowledge.mdx"}, data: docs_7 }, { info: {"path":"databases/drizzle-orm/modular-scalable-schema-design.mdx","absolutePath":"/Users/remcostoeten/code/v2.snippets/content/docs/databases/drizzle-orm/modular-scalable-schema-design.mdx"}, data: docs_8 }, { info: {"path":"databases/drizzle-orm/setup-drizzle-orm-sqlite.mdx","absolutePath":"/Users/remcostoeten/code/v2.snippets/content/docs/databases/drizzle-orm/setup-drizzle-orm-sqlite.mdx"}, data: docs_9 }], [])